// <auto-generated />
namespace FineEx.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create2));
        
        string IMigrationMetadata.Id
        {
            get { return "202007171353094_create2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
