//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineEx.Resources.Invoice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FineEx.Resources.Invoice.Invoice", typeof(Invoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (yes/no).
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash On Delivery.
        /// </summary>
        public static string CashOnDelivery {
            get {
                return ResourceManager.GetString("CashOnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select company ---.
        /// </summary>
        public static string CompanyPlaceholder {
            get {
                return ResourceManager.GetString("CompanyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string CreateInvoice {
            get {
                return ResourceManager.GetString("CreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Invoice.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string IncomingInvoice {
            get {
                return ResourceManager.GetString("IncomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select invoice type ---.
        /// </summary>
        public static string InvoiceTypePlaceholder {
            get {
                return ResourceManager.GetString("InvoiceTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select item ---.
        /// </summary>
        public static string ItemPlaceholder {
            get {
                return ResourceManager.GetString("ItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        public static string OutgoingInvoice {
            get {
                return ResourceManager.GetString("OutgoingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select payment method ---.
        /// </summary>
        public static string PaymentMethodPlaceholder {
            get {
                return ResourceManager.GetString("PaymentMethodPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Without VAT.
        /// </summary>
        public static string PriceWithoutVat {
            get {
                return ResourceManager.GetString("PriceWithoutVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select recipient ---.
        /// </summary>
        public static string RecipientPlaceholder {
            get {
                return ResourceManager.GetString("RecipientPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Invoices.
        /// </summary>
        public static string ShowInvoices {
            get {
                return ResourceManager.GetString("ShowInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Invoice ID.
        /// </summary>
        public static string UniqueInvoiceID {
            get {
                return ResourceManager.GetString("UniqueInvoiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        public static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Percentage.
        /// </summary>
        public static string VatPercentage {
            get {
                return ResourceManager.GetString("VatPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift.
        /// </summary>
        public static string VatSwiftNumberClient {
            get {
                return ResourceManager.GetString("VatSwiftNumberClient", resourceCulture);
            }
        }
    }
}
